### PR TITLE
Fix possible NullReferenceException.

### LINKED ISSUE #144: NullPointerException in EvolvioColor.java
java.lang.NullPointerException
	at evolv.io.EvolvioColor.mousePressed(EvolvioColor.java:175)
	at processing.core.PApplet.mousePressed(PApplet.java:2767)
	at processing.core.PApplet.handleMouseEvent(PApplet.java:2700)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2618)
	at processing.core.PApplet.handleDraw(PApplet.java:2429)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1540)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

Line 175 is:
cameraX = (float) evoBoard.getSelectedCreature().getPx();

### PR DESCRIPTION
**Pull request by PRabahy**
Fixes #144

### CODE REVIEW

File: src/evolv/io/EvolvioColor.java [hunk 1]
```diff
@@ -170,7 +170,7 @@ public void mousePressed() {
 				}
 			} else if (mouseX >= height + 10 && mouseX < width - 50 && evoBoard.getSelectedCreature() == null) {
 				int listIndex = (mouseY - 150) / 70;
-				if (listIndex >= 0 && listIndex < Configuration.LIST_SLOTS) {
+				if (evoBoard.getCreatureInList(listIndex) != null) {
```
Comment (NateUniAccount) [inline src/evolv/io/EvolvioColor.java]: I believe all 3 checks will be needed, getCreatureInList() doesn't check whether the index is valid, so if it isn't valid it'll throw an ArrayOutOfBoundsException

Comment (PRabahy) [inline src/evolv/io/EvolvioColor.java]: Never came up when I was testing, but sounds reasonable. Fixed.
